/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'surface':                  '#12131b',
        'surface-dim':              '#12131b',
        'surface-bright':           '#383942',
        'surface-container-lowest': '#0c0e16',
        'surface-container-low':    '#1a1b23',
        'surface-container':        '#1e1f28',
        'surface-container-high':   '#282932',
        'surface-container-highest':'#33343d',
        'surface-variant':          '#33343d',
        'surface-tint':             '#bac3ff',
        'on-surface':               '#e2e1ed',
        'on-surface-variant':       '#c4c5d7',
        'inverse-surface':          '#e2e1ed',
        'inverse-on-surface':       '#2f3039',
        'outline':                  '#8e8fa1',
        'outline-variant':          '#444655',
        'background':               '#12131b',
        'on-background':            '#e2e1ed',
        'primary':                  '#bac3ff',
        'on-primary':               '#00218d',
        'primary-container':        '#4361ee',
        'on-primary-container':     '#f4f2ff',
        'primary-fixed':            '#dee1ff',
        'primary-fixed-dim':        '#bac3ff',
        'on-primary-fixed':         '#001159',
        'on-primary-fixed-variant': '#0031c4',
        'inverse-primary':          '#2e4edc',
        'secondary':                '#b7c8e1',
        'on-secondary':             '#213145',
        'secondary-container':      '#3a4a5f',
        'on-secondary-container':   '#a9bad3',
        'secondary-fixed':          '#d3e4fe',
        'secondary-fixed-dim':      '#b7c8e1',
        'on-secondary-fixed':       '#0b1c30',
        'on-secondary-fixed-variant':'#38485d',
        'tertiary':                 '#ffb692',
        'on-tertiary':              '#562000',
        'tertiary-container':       '#ba4e00',
        'on-tertiary-container':    '#fff1eb',
        'tertiary-fixed':           '#ffdbcb',
        'tertiary-fixed-dim':       '#ffb692',
        'on-tertiary-fixed':        '#341100',
        'on-tertiary-fixed-variant':'#793000',
        'error':                    '#ffb4ab',
        'on-error':                 '#690005',
        'error-container':          '#93000a',
        'on-error-container':       '#ffdad6',
      },
      fontFamily: {
        sans:  ['Inter', 'sans-serif'],
        mono:  ['"JetBrains Mono"', '"Roboto Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg':  ['57px', { lineHeight: '64px',  letterSpacing: '-0.25px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px',  letterSpacing: '0px',     fontWeight: '600' }],
        'title-md':    ['16px', { lineHeight: '24px',  letterSpacing: '0.15px',  fontWeight: '500' }],
        'body-lg':     ['16px', { lineHeight: '24px',  letterSpacing: '0.5px',   fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px',  letterSpacing: '0.25px',  fontWeight: '400' }],
        'label-sm':    ['11px', { lineHeight: '16px',  letterSpacing: '0.5px',   fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm:      '0.25rem',
        md:      '0.75rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      spacing: {
        'xs':     '4px',
        'sm':     '12px',
        'md':     '16px',
        'lg':     '24px',
        'xl':     '32px',
        'base':   '8px',
        'gutter': '24px',
        'margin': '32px',
      },
    },
  },
  plugins: [],
};
